version: "3"
services:
  postgres:
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:4"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    # TODO get volumes working
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    # TODO get volumes working
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    # TODO get volumes working
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
