apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grider-k8s-scotthallock-net-tls
spec:
  secretName: grider-k8s-scotthallock-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grider-k8s.scotthallock.net
  dnsNames:
    - grider-k8s.scotthallock.net
