name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  cid:
    name: Build Test Publish Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v1
      - name: Log In To Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "339.0.0"
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
      - name: Get Kubernetes Cluster Credentials
        run:
          gcloud container clusters get-credentials multi-cluster
          --zone='us-west1-c'
      - name: Build Test Client
        run: |-
          docker build \
            -t scotthal/multi-client-test \
            -f ./client/Dockerfile.dev \
            ./client

      - name: Test Client
        run: |-
          docker run \
            -e CI=true \
            scotthal/multi-client-test \
            npm run test

      - name: Build And Push Client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags:
            scotthal/multi-client:latest,scotthal/multi-client:${{ github.sha }}
      - name: Build And Push Server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags:
            scotthal/multi-server:latest,scotthal/multi-server:${{ github.sha }}
      - name: Build and Push Worker
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          push: true
          tags:
            scotthal/multi-worker:latest,scotthal/multi-worker:${{ github.sha }}
      - name: Update Kubernetes Cluster
        run: |-
          kubectl apply -f k8s
          kubectl apply -f k8s-tls
          kubectl set image deployments/client-deployment client=scotthal/multi-client:$GITHUB_SHA
          kubectl set image deployments/server-deployment server=scotthal/multi-server:$GITHUB_SHA
          kubectl set image deployments/worker-deployment worker=scotthal/multi-worker:$GITHUB_SHA
