name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  cid:
    name: Build Test Publish Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Docker
        uses: docker-setup-buildx-action@v1
      - name: Log In To Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Test Client
        run: |-
          docker build \
            -t scotthal/multi-client-test \
            -f ./client/Dockerfile.dev \
            ./client

      - name: Test Client
        run: |-
          docker run \
            -e CI=true \
            scotthal/multi-client-test \
            npm run test

      - name: Build And Push Client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: scotthal/multi-client:latest
      - name: Build And Push Server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: scotthal/multi-server:latest
      - name: Build and Push Worker
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          push: true
          tags: scotthal/multi-worker:latest
